#!/usr/bin/env node
// Emits an idempotent SQL transaction that loads the Listening Party YAML into
// Supabase. Writes to stdout; nothing here touches the network.
//
//   node scripts/import/listening-party.js > /tmp/lp.sql
//
// Re-running is safe: every insert has an ON CONFLICT on the table's natural
// key, so a second run updates in place rather than duplicating. That matters
// because the YAML stays in git as the historical record, and the import may
// need replaying after a schema change.

import { readFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';
import { lit, text, num, slugify, valuesList } from './lib/sql.js';

const DATA = join(dirname(fileURLToPath(import.meta.url)), '../../src/data');

const OWNER_EMAIL = process.env.OWNER_EMAIL ?? 'alexander.jameswatts@gmail.com';
const WS_SLUG = process.env.WORKSPACE_SLUG ?? 'brothers';
const WS_NAME = process.env.WORKSPACE_NAME ?? 'Listening Party';
// Public by default: this workspace is the site that is already live at
// ilexlycalopex.github.io/listening-party and should stay readable to anyone.
const WS_VISIBILITY = process.env.WORKSPACE_VISIBILITY ?? 'public';

const read = f => yaml.load(readFileSync(join(DATA, f), 'utf-8'));

const contributors = read('contributors.yaml');
const seasonsIndex = read('seasons.yaml');
const seasonFiles = readdirSync(join(DATA, 'selections'))
  .filter(f => f.endsWith('.yaml'))
  .sort();

const out = [];
const p = s => out.push(s);

p(`-- Listening Party import — generated by scripts/import/listening-party.js`);
p(`-- ${contributors.length} contributors, ${seasonFiles.length} seasons\n`);
p('begin;\n');

// ── Workspace ─────────────────────────────────────────────────────
// The description comes from whichever season is currently active, so the
// workspace reads sensibly on the dashboard before you open it.
const activeSeason = [...seasonsIndex].reverse().find(s => s.status === 'active') ?? seasonsIndex[0];

p(`insert into public.workspaces (app, slug, name, description, visibility, owner_id)
select 'listening-party', ${lit(WS_SLUG)}, ${lit(WS_NAME)}, ${text(activeSeason?.description)},
       ${lit(WS_VISIBILITY)}::public.visibility, p.id
from public.profiles p
where p.email = ${lit(OWNER_EMAIL)}
on conflict (app, slug) do update
  set name = excluded.name,
      description = excluded.description,
      visibility = excluded.visibility;
`);

// Every later statement resolves the workspace by (app, slug) rather than
// carrying an id around, which keeps the script replayable against any project.
const WS = `(select id from public.workspaces where app = 'listening-party' and slug = ${lit(WS_SLUG)})`;

// ── Contributors ──────────────────────────────────────────────────
// user_id is deliberately left null. Chris has picks scheduled for 2027 and no
// account yet; linking a contributor to a real user is a later, manual step.
const contribRows = contributors.map((c, i) => [
  WS, lit(c.id), lit(c.name), lit(c.color), String(i),
]);

p(`insert into public.lp_contributors (workspace_id, slug, name, color, sort_order)
values
${valuesList(contribRows)}
on conflict (workspace_id, slug) do update
  set name = excluded.name, color = excluded.color, sort_order = excluded.sort_order;
`);

// ── Seasons ───────────────────────────────────────────────────────
const seasons = seasonFiles.map((file, i) => {
  const parsed = read(join('selections', file));
  const id = file.replace(/\.yaml$/, '');
  const meta = seasonsIndex.find(s => String(s.id) === id);
  return {
    id,
    file,
    // seasons.yaml is the registry and wins on presentation; the selections
    // file is the source of truth for total_weeks.
    title: meta?.title ?? parsed.title,
    description: meta?.description ?? parsed.description,
    status: meta?.status ?? 'upcoming',
    total_weeks: parsed.total_weeks,
    contributors: meta?.contributors ?? [],
    selections: parsed.selections ?? [],
    sort_order: i,
  };
});

const seasonRows = seasons.map(s => [
  WS, lit(s.id), lit(s.title), text(s.description), num(s.total_weeks),
  lit(s.status), String(s.sort_order),
]);

p(`insert into public.lp_seasons (workspace_id, slug, title, description, total_weeks, status, sort_order)
values
${valuesList(seasonRows)}
on conflict (workspace_id, slug) do update
  set title = excluded.title, description = excluded.description,
      total_weeks = excluded.total_weeks, status = excluded.status,
      sort_order = excluded.sort_order;
`);

// ── Season rosters ────────────────────────────────────────────────
const rosterRows = seasons.flatMap(s =>
  s.contributors.map((slug, i) => [lit(s.id), lit(slug), String(i)])
);

if (rosterRows.length) {
  p(`insert into public.lp_season_contributors (season_id, contributor_id, sort_order)
select s.id, c.id, v.sort_order::int
from (values
${valuesList(rosterRows)}
) as v(season_slug, contributor_slug, sort_order)
join public.lp_seasons s      on s.workspace_id = ${WS} and s.slug = v.season_slug
join public.lp_contributors c on c.workspace_id = ${WS} and c.slug = v.contributor_slug
on conflict (season_id, contributor_id) do update set sort_order = excluded.sort_order;
`);
}

// ── Selections ────────────────────────────────────────────────────
const selectionRows = seasons.flatMap(s =>
  s.selections.map(sel => [
    lit(s.id),
    num(sel.week),
    num(sel.year_slot),
    lit(sel.contributor),
    text(sel.album),
    text(sel.artist),
    lit(sel.status),
    text(sel.artwork_url),
    text(sel.links?.wikipedia),
    text(sel.links?.spotify),
    text(sel.links?.youtube),
    text(sel.notes),
  ])
);

p(`insert into public.lp_selections (
  workspace_id, season_id, contributor_id, week, year_slot,
  album, artist, status, artwork_url,
  link_wikipedia, link_spotify, link_youtube, notes
)
select ${WS}, s.id, c.id, v.week::int, v.year_slot::int,
       v.album, v.artist, v.status, v.artwork_url,
       v.wikipedia, v.spotify, v.youtube, v.notes
from (values
${valuesList(selectionRows)}
) as v(season_slug, week, year_slot, contributor_slug, album, artist, status,
       artwork_url, wikipedia, spotify, youtube, notes)
join public.lp_seasons s      on s.workspace_id = ${WS} and s.slug = v.season_slug
join public.lp_contributors c on c.workspace_id = ${WS} and c.slug = v.contributor_slug
on conflict (season_id, week, contributor_id) do update
  set year_slot = excluded.year_slot,
      album = excluded.album, artist = excluded.artist,
      status = excluded.status, artwork_url = excluded.artwork_url,
      link_wikipedia = excluded.link_wikipedia,
      link_spotify = excluded.link_spotify,
      link_youtube = excluded.link_youtube,
      notes = excluded.notes;
`);

p('commit;');

// A self-check in the emitted SQL, so a bad import announces itself instead of
// leaving a half-populated season to be discovered later. It sits after COMMIT
// on purpose: a syntax error here must not roll the import back.
const total = seasons.reduce((n, s) => n + s.selections.length, 0);
const completed = seasons.reduce(
  (n, s) => n + s.selections.filter(x => x.status === 'completed').length, 0
);
p(`
-- expected: ${contributors.length} contributors, ${seasons.length} seasons,
--           ${total} selections (${completed} completed)
select
  (select count(*) from public.lp_contributors sel where sel.workspace_id = ${WS}) as contributors,
  (select count(*) from public.lp_seasons      sel where sel.workspace_id = ${WS}) as seasons,
  (select count(*) from public.lp_selections   sel where sel.workspace_id = ${WS}) as selections,
  (select count(*) from public.lp_selections   sel where sel.workspace_id = ${WS}
     and sel.status = 'completed') as completed;`);

process.stdout.write(out.join('\n') + '\n');
